### ============================================================
### PLAN DE PRUEBAS - ORDEN DE EXTRACCIÓN 
### ============================================================

### CP-1, CP-3, CP-5 y CP-6: Flujo Normal Exitoso (Saldo, Token y Registro)
### CP-3 Datos de entrada: id_cliente: 1; monto: 10000 (datos válidos)
###      Resultado esperado: El sistema verifica el saldo. El saldo es suficiente.
### CP-5 Resultado esperado: El sistema genera un token de número aleatorio si las verificaciones anteriores son correctas.
### CP-6 Datos de entrada: id_cuenta: 1; monto: 10000; token: numero_aleatorio
###      Resultado esperado: El sistema verifica los datos ingresados. Datos correctos. 
###                          Sistema registra la órden de extracción y muestra mensaje "¡Órden generada con éxito!"
POST http://localhost:3000/api/generar-extraccion
Content-Type: application/json

{
  "id_cliente": 1,
  "monto": 10000
}


### CP-2: Verificar monto (Dato no válido)
### Objetivo: Verificar monto.
### Datos de entrada: monto: 15000 (dato no válido)
### Resultado esperado: El sistema verifica el monto. Monto no válido. 
###                    Sistema muestra mensaje "El monto debe ser múltiplo de $10.000"
POST http://localhost:3000/api/generar-extraccion
Content-Type: application/json

{
  "id_cliente": 1,
  "monto": 15000
}


### CP-4: Verificar saldo (Saldo insuficiente)
### Objetivo: Verificar saldo.
### Datos de entrada: id_cliente: 1; monto: 9999999 (saldo insuficiente)
### Resultado esperado: El sistema verifica el saldo. El saldo es insuficiente. 
###                    Sistema muestra mensaje "Saldo insuficiente. Tu saldo actual es de $..."
POST http://localhost:3000/api/generar-extraccion
Content-Type: application/json

{
  "id_cliente": 1,
  "monto": 100000000
}


### CP-7: Registrar órden de extracción (Datos incorrectos)
### Objetivo: Registrar órden de extracción.
### Datos de entrada: id_cuenta: 999; monto: 10000000; token: ""
### Resultado esperado: El sistema verifica los datos ingresados. Datos incorrectos. 
###                    Sistema no registra la órden de extracción y muestra mensaje con el error.
POST http://localhost:3000/api/generar-extraccion
Content-Type: application/json

{
  "id_cliente": 999,
  "monto": 10000000
}

### ============================================================
### PLAN DE PRUEBAS - REALIZAR TRANSFERENCIA
### ============================================================

### CP-1, CP-3, CP-5 y CP-7: Flujo Normal Exitoso de Transferencia
### CP-1 (El monto es válido)
### CP-5: Verificar cuenta destino (Cuenta existente)
### CP-3 (El saldo es suficiente)
### CP-7 (Debita origen, acredita destino, registra transferencia)
### Resultado esperado: Sistema realiza la operación y muestra “¡Transferencia realizada con éxito!”
POST http://localhost:3000/api/transferencia
Content-Type: application/json

{
  "id_cliente": 1,
  "cbuAliasDestino": "matiasgon",
  "monto": 1500,
  "id_concepto_transferencia": 8
}


### CP-2: Verificar monto (Dato no válido)
### Objetivo: Verifica que el monto sea válido.
### Datos de entrada: monto: -500 (dato no válido)
### Resultado esperado: Los datos ingresados son inválidos. Sistema muestra mensaje de error.
POST http://localhost:3000/api/transferencia
Content-Type: application/json

{
  "id_cliente": 1,
  "cbuAliasDestino": "matiasgon",
  "monto": -500,
  "id_concepto_transferencia": 8
}


### CP-4: Verificar saldo (Saldo insuficiente)
### Objetivo: Verifica que el saldo sea suficiente.
### Datos de entrada: id_cliente: 1; monto: 9999999 (saldo insuficiente)
### Resultado esperado: El saldo es insuficiente. Sistema muestra: “Saldo insuficiente. Tu saldo actual es de $...”
POST http://localhost:3000/api/transferencia
Content-Type: application/json

{
  "id_cliente": 1,
  "cbuAliasDestino": "matiasgon",
  "monto": 9999999,
  "id_concepto_transferencia": 8
}

### CP-6: Verificar cuenta destino (Cuenta inexistente)
### Objetivo: Verificar que la cuenta destino exista.
### Datos de entrada: cbuAliasDestino: "alias.falso" (dato no válido)
### Resultado esperado: Cuenta inexistente. Sistema muestra mensaje: “La cuenta de destino no existe.”
GET http://localhost:3000/api/transferencia/destino/alias.falso

### CP-8: Registrar transferencia (Datos incorrectos)
### Objetivo: Probar el rechazo ante datos inconsistentes en la transacción.
### Datos de entrada: id_cliente: 999; monto: 1500
### Resultado esperado: Datos incorrectos. Sistema muestra mensaje según el error.
POST http://localhost:3000/api/transferencia
Content-Type: application/json

{
  "id_cliente": 999,
  "cbuAliasDestino": "matiasgon",
  "monto": 1500,
  "id_concepto_transferencia": 8
}


### CP-9: Agendar contacto
### Objetivo: Guardar contacto tras transferencia exitosa.
### Datos de entrada: id_cliente: 3; alias_destinatario: "matiasgon"; nombre_contacto: "Matías"
### Resultado esperado: El sistema guarda los datos del destinatario.
POST http://localhost:3000/api/contactos
Content-Type: application/json

{
  "id_cliente": 3,
  "cbu_destinatario": "098765432109876543218",
  "alias_destinatario": "matiasgon",
  "nombre_contacto": "Matías"
}